/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chaser.ui;

import chaser.logiikka.DataHandler;
import chaser.logiikka.FileMaker;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Samuli Peltonen
 */
public class GUI extends javax.swing.JFrame {

    private DataHandler dh;
    private ArrayList<String> tiedostot;
    private String tiedostoPolku;

    public GUI() throws IOException, URISyntaxException {
        this.tiedostot = new ArrayList<>();
        this.tiedostoPolku = etsiTiedostopolku();
        this.dh = new DataHandler(this.tiedostoPolku);

        luoKansio();
        etsiTiedostot();
        initComponents();
    }

    private void luoKansio() throws IOException, URISyntaxException {
        File kansio = new File(this.tiedostoPolku + "/StockData");
        kansio.mkdir();

    }

    private String etsiTiedostopolku() throws URISyntaxException {
        File path = new File(GUI.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath());
        return path.getParent();
    }

    private void etsiTiedostot() {
        try {
            File kansio = new File(tiedostoPolku + "/StockData");
            tiedostot.clear();
            for (File f : kansio.listFiles()) {
                if (!tiedostot.contains(f.getName())) {
                    this.tiedostot.add(f.getName());
                }
            }
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Url = new javax.swing.JTextField();
        luotavanTiedostonNimi = new javax.swing.JTextField();
        Hae = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ListaaTiedostot = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListatutTiedostot = new javax.swing.JTextArea();
        dataHakuAlku = new javax.swing.JTextField();
        datanHakuLoppu = new javax.swing.JTextField();
        Piirtaja = new javax.swing.JButton();
        mapattavaTiedosto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("StockChaser");

        jLabel2.setText("Datan hakeminen \"google.com/finance\" sivustolta");

        Url.setToolTipText("Kirjoita tähän url");
        Url.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrlActionPerformed(evt);
            }
        });

        luotavanTiedostonNimi.setToolTipText("Kirjoita tähän luotavan tiedoston nimi");
        luotavanTiedostonNimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luotavanTiedostonNimiActionPerformed(evt);
            }
        });

        Hae.setText("Hae");
        Hae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HaeActionPerformed(evt);
            }
        });

        jLabel3.setText("URL");

        jLabel4.setText("Luotavan tiedoston nimi");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        ListaaTiedostot.setText("Listaa tiedostot");
        ListaaTiedostot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaaTiedostotActionPerformed(evt);
            }
        });

        ListatutTiedostot.setColumns(20);
        ListatutTiedostot.setRows(5);
        jScrollPane2.setViewportView(ListatutTiedostot);

        dataHakuAlku.setToolTipText("Monennestako datapisteestä keraaminen aloitetaan. Maksimi on 249.");

        datanHakuLoppu.setToolTipText("Montako datapistettä kerätään. Maksimi on 250");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(luotavanTiedostonNimi)
                    .addComponent(Url, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(164, 164, 164))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(ListaaTiedostot))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dataHakuAlku, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(datanHakuLoppu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Hae)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(luotavanTiedostonNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hae, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataHakuAlku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datanHakuLoppu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListaaTiedostot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        Piirtaja.setText("Piirrä");
        Piirtaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiirtajaActionPerformed(evt);
            }
        });

        mapattavaTiedosto.setToolTipText("Kirjoita tähän piirrettävän tiedoston nimi ilman tiedostopäätteitä");

        jLabel5.setText("Tiedoston valinta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Piirtaja)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mapattavaTiedosto, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(mapattavaTiedosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Piirtaja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HaeActionPerformed
        String url = Url.getText();
        String tiedostonNimi = luotavanTiedostonNimi.getText();

        boolean onnistui = true;
        try {
            dh.makeFileFromUrl(tiedostonNimi, url, dataHakuAlku.getText(), datanHakuLoppu.getText());
        } catch (Exception ex) {
            jTextArea1.setText("Jotain meni pieleen, tiedostoa ei luotu");
            onnistui = false;
        }
        if (onnistui) {
            jTextArea1.setText("Tiedosto luotiin!");
        }

        etsiTiedostot();
    }//GEN-LAST:event_HaeActionPerformed

    private void luotavanTiedostonNimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luotavanTiedostonNimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luotavanTiedostonNimiActionPerformed

    private void UrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UrlActionPerformed

    private void ListaaTiedostotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaaTiedostotActionPerformed
        etsiTiedostot();
        String listaString = "";
        for (String s : this.tiedostot) {
            listaString = listaString + s + "\n";
        }
        ListatutTiedostot.setText("Tiedostot löytyvät kansiosta:\n" + tiedostoPolku + "/StockData" + "\n\n" + "Tiedostot:\n" + listaString);
    }//GEN-LAST:event_ListaaTiedostotActionPerformed

    private void PiirtajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiirtajaActionPerformed
        JFrame f = new JFrame("Grapher");
        f.setVisible(true);
        f.setSize(1000, 700);
        int[] dimensio = new int[]{1000, 700};
        int[] reunat = new int[]{100, 50};
        String tiedostoNimi = mapattavaTiedosto.getText();
        Grapher graph = new Grapher(dimensio, reunat, tiedostoNimi, "Close", this.dh, this.tiedostoPolku);
        f.add(graph);
    }//GEN-LAST:event_PiirtajaActionPerformed

    /**
     * @param args the command line arguments
     */
    //Tartteekohan tätä mihinkään?
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hae;
    private javax.swing.JButton ListaaTiedostot;
    private javax.swing.JTextArea ListatutTiedostot;
    private javax.swing.JButton Piirtaja;
    private javax.swing.JTextField Url;
    private javax.swing.JTextField dataHakuAlku;
    private javax.swing.JTextField datanHakuLoppu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField luotavanTiedostonNimi;
    private javax.swing.JTextField mapattavaTiedosto;
    // End of variables declaration//GEN-END:variables
}
